// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAgenda.API.Infrastructure.Persistence;

#nullable disable

namespace MyAgenda.API.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20251122064521_SeedContacts")]
    partial class SeedContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MyAgenda.API.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(156),
                            Email = "ana.silva@example.com",
                            Name = "Ana Silva",
                            Phone = "(11) 98876-1234"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(158),
                            Email = "bruno.santos@example.com",
                            Name = "Bruno Santos",
                            Phone = "(21) 99745-6789"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(159),
                            Email = "carla.almeida@example.com",
                            Name = "Carla Almeida",
                            Phone = "(31) 98432-5566"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(160),
                            Email = "diego.rodrigues@example.com",
                            Name = "Diego Rodrigues",
                            Phone = "(41) 99123-7890"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(161),
                            Email = "elaine.costa@example.com",
                            Name = "Elaine Costa",
                            Phone = "(51) 98765-4321"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(162),
                            Email = "fabio.mendes@example.com",
                            Name = "Fabio Mendes",
                            Phone = "(71) 98123-4455"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(163),
                            Email = "gabriela.torres@example.com",
                            Name = "Gabriela Torres",
                            Phone = "(81) 98654-7788"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(164),
                            Email = "henrique.lima@example.com",
                            Name = "Henrique Lima",
                            Phone = "(91) 98321-0099"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(165),
                            Email = "isabela.martins@example.com",
                            Name = "Isabela Martins",
                            Phone = "(62) 99234-5678"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 22, 6, 45, 21, 549, DateTimeKind.Utc).AddTicks(166),
                            Email = "joao.pereira@example.com",
                            Name = "João Pereira",
                            Phone = "(85) 99543-2211"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
